spring:
  application:
    name: demo-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.168.1.248:8848
        namespace: b60e1e77-d986-4d0e-919e-a8de3a5f034b
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: daisyday-demon7
#          uri: lb://customer
#          predicates:
#           - Path=/customer/**
#          filters:
#           - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          login-client2:
            provider: spring
            client-id: login-client2
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid,profile
            client-name: Spring
        provider:
          spring:
            authorization-uri: http://www.xg.com:9000/oauth2/authorize
            token-uri: http://www.xg.com:9000/oauth2/token
            jwk-set-uri: http://www.xg.com:9000/oauth2/jwks

server:
  port: 8091
  ssl:
    enabled: true
    key-alias: root
    key-store-password: 189@yuan
    key-store: classpath:dlt.p12
    key-store-type: PKCS12


